### ISSUE TITLE
Add validation to lat long values in populate map bounds

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/CyAN-Web#229]
We could limit bounds to just the region relevant to this application
in the form can setup the validator like so:

![image](https://user-images.githubusercontent.com/23640741/201771500-b3df0131-aded-4316-96e1-99e229be3402.png)

Patterns look like so: 
`latitudePattern: RegExp =
    /^(\+|-)?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$/;
  longitudePattern: RegExp =
    /^(\+|-)?(?:180(?:(?:\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,6})?))$/;`

https://ihateregex.io/playground/

**Comment by ghost** [comment]
I kind of like the ability to still have valid bounds outside of the relevant region. For example, if a user cares about north/south bounds, but not east/west, so puts -180/180 for them, they should be able to do that. That said, there could be merit to keeping within -90/90, -180/180, tho currently I don't see a problem with entering, say -1000/1000 for E/W if user is trying to guarantee those are ignored.
