### ISSUE TITLE
Put mcode and pcode in dropdown menu

### ISSUE THREAD

**Issue by ghost** [USGS-WiM/CyAN-Web#237]
Keith would like to see the pcode/mcode in paratheses after the parameter/method name.

**Comment by lprivette** [comment]
Is this supposed to be an each dropdown? I'm running 237 locally and not seeing it but maybe I'm not looking in the right place

**Comment by ghost** [comment]
Instead of cross-referencing the pcode in the popup with the pcode in parathesis in the dropdown menus, I replaced the pcode in the popups with the short_name
